Repository projectdiscovery/interactsh, pull requests merged in 2021-12, with the labels that each got.

#123 Update README.md
  README.md
Labels: Priority: Low, Type: Enhancement

#128 Add listening ports as argument
  cmd/interactsh-server/main.go
  cmd/interactsh-server/smb_server.py
  pkg/server/dns_server.go
  pkg/server/http_server.go
  pkg/server/server.go
  pkg/server/smb_server.go
  pkg/server/smtp_server.go
Labels: Type: Enhancement

#131 Parse SearchRequest and build Interaction object
  cmd/interactsh-client/main.go
  pkg/server/ldap_server.go
Labels: Type: Enhancement

#143 Add netifaces pip package in Dockerfile
  cmd/interactsh-server/Dockerfile
Labels: Type: Bug

#149 Making ACME/TLS optional
  cmd/interactsh-server/main.go
Labels: Status: Review Needed, Type: Enhancement

#55 Adding ldap support
  README.md
  cmd/interactsh-client/main.go
  cmd/interactsh-server/main.go
  cmd/interactsh-server/smb_server.py
  go.mod
  go.sum
  pkg/server/ftp_server.go
  pkg/server/http_server.go
  pkg/server/ldap_server.go
  pkg/server/server.go
Labels: Status: Review Needed, Type: Enhancement

#155 Making app CNAME optional
  cmd/interactsh-server/main.go
  pkg/server/dns_server.go
  pkg/server/server.go
Labels: Status: Completed, Type: Bug

#154 Adding optional support for HTTP fallback on HTTPS failure
  cmd/interactsh-client/main.go
  pkg/client/client.go
Labels: Status: Review Needed, Type: Enhancement
