Repository projectdiscovery/interactsh, pull requests merged in 2022-05, with the labels that each got.

#274 Disable retries on registration
  go.mod
  go.sum
  pkg/client/client.go
Labels: Status: Review Needed, Type: Enhancement

#277 Bumping retryablehttp library
  go.mod
  go.sum
Labels: Type: Maintenance

#285 Add verbose instead of errors for interactsh-client
  cmd/interactsh-client/main.go
  pkg/client/client.go
Labels: Status: Review Needed

#289 Cleanup default storage from stale OCSP entries
  cmd/interactsh-server/main.go
  pkg/server/acme/acme_certbot.go
Labels: Status: Review Needed, Type: Maintenance

#286 Adding Multi-Domain support
  README.md
  cmd/interactsh-server/main.go
  pkg/options/server_options.go
  pkg/server/acme/acme_certbot.go
  pkg/server/dns_server.go
  pkg/server/http_server.go
  pkg/server/server.go
  pkg/server/smtp_server.go
  pkg/stringslice/stringslice.go
Labels: Status: Completed, Type: Enhancement
