Repository projectdiscovery/interactsh, pull requests merged in 2022-08, with the labels that each got.

#347 Added custom DNS records server + fixed bugs
  cmd/interactsh-server/example-custom-records.yaml
  cmd/interactsh-server/main.go
  pkg/options/server_options.go
  pkg/server/dns_server.go
  pkg/server/server.go
Labels: Status: Review Needed

#369 Improving gitignore
  .gitignore
Labels: Status: Review Needed, Type: Maintenance

#368 Extending metrics endpoint
  cmd/interactsh-server/main.go
  go.mod
  go.sum
  pkg/options/server_options.go
  pkg/server/dns_server.go
  pkg/server/ftp_server.go
  pkg/server/http_server.go
  pkg/server/ldap_server.go
  pkg/server/metrics.go
  pkg/server/server.go
  pkg/server/smb_server.go
  pkg/server/smtp_server.go
Labels: Status: Review Needed, Type: Enhancement
