Repository projectdiscovery/interactsh, pull requests merged in 2022-01, with the labels that each got.

#162 Use certmagic + bugfixing for DNS server
  cmd/interactsh-server/main.go
  go.mod
  go.sum
  pkg/server/acme/acme.go
  pkg/server/acme/acme_certbot.go
  pkg/server/acme/records_store.go
  pkg/server/dns_server.go
  pkg/server/ftp_server.go
  pkg/server/http_server.go
  pkg/server/ldap_server.go
  pkg/server/server.go
  pkg/server/smtp_server.go
Labels: Status: Completed

#160 Replaced internal kv store with goburrow/cache
  go.mod
  go.sum
  pkg/client/client.go
  pkg/server/http_server.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: Status: Review Needed, Type: Bug

#165 Updating tls logic after switching to certmagic from caddy
  pkg/server/ldap_server.go
Labels: Status: Review Needed, Type: Bug

#172 Added random server pickup + misc changes to client
  cmd/interactsh-client/main.go
  pkg/client/client.go
Labels: Status: Review Needed

#183 Adding goflags support
  cmd/interactsh-client/main.go
  cmd/interactsh-server/main.go
  go.mod
  go.sum
  pkg/options/client_options.go
  pkg/options/server_options.go
  pkg/options/utils.go
  pkg/server/dns_server.go
  pkg/server/server.go
Labels: Type: Enhancement

#195 Fixes to interactsh client and server loggings
  cmd/interactsh-server/main.go
  pkg/client/client.go
  pkg/server/acme/acme_certbot.go
  pkg/server/dns_server.go
Labels: Status: Completed

#209 Making client connect with user provided protocol
  pkg/client/client.go
Labels: Type: Bug
